### ISSUE TITLE
A bug!

### ISSUE THREAD

**Issue by nabily4e-dev** [202212-GIZ-YE-FEW/mad-libs-amazing-team#23]
Clone the repo and try to figure out why the contents are not appearing?!!

**Comment by MariaAbdullah97** [comment]
ok

**Comment by nabily4e-dev** [comment]
![Image](https://user-images.githubusercontent.com/75049983/215976648-a7adf75f-3c91-47a3-98e0-815253eccee3.png)

**Comment by nabily4e-dev** [comment]
Please all, confirm working code.

**Comment by Abrar-Abdulwahed** [comment]
works well

**Comment by MarwanBz** [comment]
working thx
