### ISSUE TITLE
"Mad Libs" what is it?!

### ISSUE THREAD

**Issue by nabily4e-dev** [202212-GIZ-YE-FEW/mad-libs-amazing-team#4]
See [wikipedia](https://en.wikipedia.org/wiki/Mad_Libs). Yes, I know this section is short, do not skip this, please read what Mad Libs is or the rest of this will make no sense. In normal mad libs, you usually just insert the word, but in this version, it's more like a "fill in the blank" of an existing story.

**Comment by MarwanBz** [comment]
done

**Comment by Abrar-Abdulwahed** [comment]
we got it 👍🏼

**Comment by MariaAbdullah97** [comment]
done
