### ISSUE TITLE
Collaboration requirements!

### ISSUE THREAD

**Issue by nabily4e-dev** [202212-GIZ-YE-FEW/mad-libs-amazing-team#5]
Please don't split the code. Write every line of code together. In each group, every person should understand every line of code.

**Comment by Abrar-Abdulwahed** [comment]
We will be cooperative in the way our group name means, amazing team🎉

**Comment by MariaAbdullah97** [comment]
ok our amazing leader

**Comment by MarwanBz** [comment]
yes we will do our best!
