### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by nabily4e-dev** [202212-GIZ-YE-FEW/mad-libs-amazing-team#9]
When the screen is small, the story should take the full width of the screen. When the screen is larger, as on a computer. Values "small" and "large" are up to you to decide.

**Comment by MariaAbdullah97** [comment]
am doing my best to do it

**Comment by MariaAbdullah97** [comment]
done

**Comment by nabily4e-dev** [comment]
Check the code after update, and try to fix the responsiveness again.
